services:
    db:
        container_name: virtuoso-db
        image: tenforce/virtuoso:1.3.2-virtuoso7.2.5.1
        environment:
            SPARQL_UPDATE: "true"
            DEFAULT_GRAPH: "https://www.dalicc.net/ld"
        volumes:
            - ./virtuoso_data:/data
        ports:
            - "8890:8890"
    api:
        container_name: dalicc-api
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - "8002:80"
        volumes:
            - .:/app
        entrypoint: ['/start-reload.sh']
        environment:
            - DB_URL=http://virtuoso-db:8890/sparql
            - REASONER_URL=http://dalicc-reasoner:80/reasoner
    reasoner:
        container_name: dalicc-reasoner
        build:
            context: ./reasoner/
            dockerfile: Dockerfile
        ports:
            - "8190:80"
        volumes:
            - ./reasoner:/app
        entrypoint: ['/start-reload.sh']
        environment:
            - DB_URL=http://virtuoso-db:8890/sparql
volumes:
  db_data: {}
